install: 
	gcc  "$HOME/Documents/Projet/CY_Trucks/progc/Traitement_s/main.c" -o "$HOME/Documents/Projet/CY_Trucks/exec"

all:
	gcc  "$HOME/Documents/Projet/CY_Trucks/progc/Traitement_s/main.c" -o "$HOME/Documents/Projet/CY_Trucks/exec"


clear:
	rm -rf "$HOME/Documents/Projet/CY_Trucks/exec"

clean:
	rm -rf "$HOME/Documents/Projet/CY_Trucks/exec"

